### ISSUE TITLE
controller keeps retrying plan even once plan is delete

### ISSUE THREAD

**Issue by rmweir** [rancher/system-upgrade-controller#36] opened 2020-02-21 19:31 UTC
**Version**

v0.3.0-m4

**Platform/Architecture**

linux amd64

**Describe the bug**

If an apply-k3s pod is erroring, the controller continues to attempt to run it even after the plan is deleted. If the pod is delete another one is created. I don't see any deployment or replicaset for this. This continues even if another plan is applied with the same name as the deleted plan.

**To Reproduce**

1. apply a plan with an incorrect image name
2. wait for apply-k3s pod to be created and error
3. delete plan and delete pod
4*. delete another plan with name of deleted plan that has proper image name

**Expected behavior**

Controller stops trying to execute plan and does not start a new pod if deleted.
Controller only run the new plan if same name is used.

**Actual behavior**

Controller keeps trying to execute plan.
Controller attempts to apply old plan and new plan (separate pods).

**Comment by dweomer** [comment] 2020-02-22 17:47
@rmweir there are a couple of things going on here, one of which is a complication, I think, with the cause of #25 (which I have an outstanding PR to fix: rancher/wrangler#66).

Another issue may be one of assumptions: for so long as a *Plan* exists in a cluster it should be understood as an outstanding intent to mutate nodes subject to its selection criteria (which includes upt-to-date-ness).

**Comment by dweomer** [comment] 2020-02-26 00:38
This should be fixed via #30

**Closed by dweomer** 2020-02-26 00:38 UTC
Labels: bug
