### ISSUE TITLE
Plan not found

### ISSUE THREAD

**Issue by Robbilie** [rancher/system-upgrade-controller#203] opened 2022-04-29 11:04 UTC
**Version**
0.9.1

**Platform/Architecture**
linux-amd64

**Describe the bug**
I am running rke2 and installed the controller according to the docs:
https://docs.rke2.io/upgrade/automated_upgrade/
I did try setting a channel but am falling back to setting a version now.
i labeled the node rke2-upgrade: "true"
i am running rke2 v1.23.5+rke2r1 and am trying to upgrade to v1.23.6+rke2r1
i have 1 master node and 2 agent nodes

the logoutput:
```
time="2022-04-29T11:00:16Z" level=debug msg="PLAN STATUS HANDLER: plan=system-upgrade/server-plan@4670979, status={Conditions:[] LatestVersion: LatestHash: Applying:[]}" func="github.com/sirupsen/logrus.(*Entry).Logf" file="/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314"
time="2022-04-29T11:00:16Z" level=debug msg="PLAN GENERATING HANDLER: plan=system-upgrade/server-plan@4670979, status={Conditions:[{Type:LatestResolved Status:True LastUpdateTime:2022-04-29T11:00:16Z LastTransitionTime: Reason:Version Message:}] LatestVersion:v1.23.6-rke2r1 LatestHash:d5c507264ef83171925233cdeebe1f8a21614263918690682ef945fe Applying:[]}" func="github.com/sirupsen/logrus.(*Entry).Logf" file="/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314"
time="2022-04-29T11:00:16Z" level=debug msg="DesiredSet - Created batch/v1, Kind=Job system-upgrade/apply-server-plan-on-decgn-pr-vmcq-k8s-with-d5c507264ef83-d9397 for system-upgrade-controller system-upgrade/server-plan" func="github.com/sirupsen/logrus.(*Entry).Logf" file="/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314"
time="2022-04-29T11:00:16Z" level=error msg="error syncing 'system-upgrade/server-plan': handler system-upgrade-controller: plans.upgrade.cattle.io \"server-plan\" not found, handler system-upgrade-controller: plans.upgrade.cattle.io \"server-plan\" not found, requeuing" func="github.com/sirupsen/logrus.(*Entry).Logf" file="/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314"
```

watching jobs in the namespace there briefly appears one and immediatly disappears:
```
system-upgrade   apply-server-plan-on-decgn-pr-vmcq-k8s-with-d5c507264ef83-d9397   0/1                      0s
```

one additional note, i am using fluxcd with the cluster though i am not sure if this is interfering here since it doesnt touch the status fields and no status is ever set on the plans nor any events appear…

**To Reproduce**
setup rke2 cluster
apply controller
apply plans

**Expected behavior**
successful node upgrades

**Actual behavior**
even initializing the upgrade fails

**Additional context**

**Comment by comphilip** [comment] 2022-05-05 02:39
Have same problem in my 3 K3S clusters. Deleting existed system-upgrade-controller pod and let K3S creates a new one will fixed the problem.

**Comment by Robbilie** [comment] 2022-05-05 08:14
i did end up removing the controller and the plans and created them again and it fixed it. really annoying for a cluster thats completly setup using IAC with ansible and flux to have to possibly manually fix some stuff

**Comment by dweomer** [comment] 2022-06-04 05:39
The not found error for the plan is weird, as are the disappearing jobs. This suggests that something, possibly fluxcd, is fighting with the SUC as it updates the status of a plan. Is it possible fluxcd is recreating the plan after SUC updates it? If it doesn't honor the .status subfield as mutable it might think it needs to reconcile drift and recreate.

**Comment by comphilip** [comment] 2022-07-04 02:11
It is not related to fluxcd. I apply plans manually and the issues still existed.

After using system-upgrade-controller for about a year, it is far from stable. Very disappointed.

**Comment by dweomer** [comment] 2022-07-10 22:52
> It is not related to fluxcd. I apply plans manually and the issues still existed.
> 
> 
> 
> After using system-upgrade-controller for about a year, it is far from stable. Very disappointed.

That's a bummer and I am sorry. If you haven't already, can you create an issue with a full repro description if not sample setup (k3d, kind, or vagrant)? Please include the plan(s) that leads to instability you have witnessed.

**Comment by reefland** [comment] 2022-07-21 02:36
Have same symptom with ArgoCD.  After some troubleshooting, I have the CRD via kustomize:
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: datasource=docker image=rancher/system-upgrade-controller
  - https://github.com/rancher/system-upgrade-controller/releases/download/v0.9.1/crd.yaml
 ```

That CRD is applied, however the System Upgrade Controller is trying to replace the CRD and ArgoCD puts back its copy from above.  The two are constantly fighting and the logs show the sync error on the plans.

In ArgoCD I disabled the self-heal to allow SUC to update the CRD, immediately the logs are stable and the error message goes away.  This is the DIFF that ArgoCD shows on the CRD created:

![image](https://user-images.githubusercontent.com/16230914/180114998-c3e8f74a-b3cf-422e-a2aa-18b9acf482eb.png)

I don't understand why the downloaded CRD is different than the one SUC is trying to use....  but as long as I allow these to be out of sync it's working.

SUC is using `image: 'rancher/system-upgrade-controller:v0.9.1'`

**Comment by Robbilie** [comment] 2022-07-21 13:52
can confirm, i dont have any errors when i drop the CRDs from my kustomization, this only works though because the plan crd is already in the cluster, starting the controller and trying to apply the plan immediatly after obviously doesnt work, because the CRD is only there after pod start…

solutions could be disabling the applying of CRDs from within the controller or fixing the CRD

**Comment by dweomer** [comment] 2022-07-21 22:53
Thank you @reefland and @Robbilie for the additional detail.

**Comment by Robbilie** [comment] 2022-07-27 21:09
@dweomer is there actually a reason for why the controller registers the CRD? Relying on it kind of encourages manual processes and for infrastructure as code approaches it is redundant, possibly even error prone like this bug shows :)

**Comment by texasbobs** [comment] 2022-08-02 14:27
We're having this issue on 9.1 as well and we do not manually deploy the CRD yaml file.

**Comment by dweomer** [comment] 2022-08-02 15:06
> @dweomer is there actually a reason for why the controller registers the CRD? Relying on it kind of encourages manual processes and for infrastructure as code approaches it is redundant, possibly even error prone like this bug shows :)

Hmm, I thought I had responded to this. The programmatic CRD registration was a pattern established by other projects/efforts that leveraged rancher/wrangler and it helped sidestep some order-of-operations issues that I ran into while developing SUC (while learning k8s controllers and wrangler).

The CRD manifest was something asked for by a customer, IIRC, with the build/run-time generation implemented by @brandond (in consultation with me and the rest of the team). A fix for this downstream conflict will require some nuance to satisfy both modes of CRD deployment and likely some adherence to proper CR versioning.

While I no longer work for SUSE/Rancher I do not want folks to feel left in the lurch. I hope to work on and validate a fix sometime soon but cannot promise availability.

**Comment by texasbobs** [comment] 2022-08-02 15:15
> 
> The CRD manifest was something asked for by a customer, IIRC, with the build/run-time generation implemented by @brandond (in consultation with me and the rest of the team). A fix for this downstream conflict will require some nuance to satisfy both modes of CRD deployment and likely some adherence to proper CR versioning.

That was us that had asked for the CRD yaml to be included in the deployment manifest.  Instead, it got added to the release assets and is still not in the manifest.  Since the _fix_ didn't really solve our problem, we split plans from the controller so Flux2 can successfully apply all of the files. Once the CRD is dynamically created, the plans can then be applied.

**Comment by Robbilie** [comment] 2022-08-02 15:33
@dweomer i mean my PR should fix the issue now, although when there are mutliple plan crd versions that might change, its just that its kinda redundant to have both ways apply the crds, as long as both use the same source it shouldnt be an issue i guess

**Closed** 2022-08-02 22:43 UTC

**Comment by brandond** [comment] 2022-08-02 23:37
I'm not convinced that the Plan CRD change is the root cause of the issue. In https://github.com/rancher/system-upgrade-controller/issues/206#issuecomment-1183725985 I saw Not Found errors for both the plan and job resources, and this what when I just ran the controller directly without pre-installing the CRDs. I think there's something else going on with the wrangler informer caches.

**Comment by Robbilie** [comment] 2022-08-26 06:30
@brandond cluster was upgraded to v1.24.4+rke2r1 without any manual intervention this time :)

**Comment by reefland** [comment] 2022-08-30 17:50
I still needed manual intervention from `v1.24.3+k3s1` to `v1.24.4+k3s1`, it detected the plan changes made by renovate, but couldn't do anything, just had errors like this over and over:
```
time="2022-08-30T17:29:40Z" level=error msg="error syncing 'system-upgrade/k3s-worker-plan': handler system-upgrade-controller: plans.upgrade.cattle.io \"k3s-worker-plan\" not found, requeuing"
time="2022-08-30T17:29:40Z" level=error msg="error syncing 'system-upgrade/k3s-control-node-plan': handler system-upgrade-controller: plans.upgrade.cattle.io \"k3s-control-node-plan\" not found, handler system-upgrade-controller: plans.upgrade.cattle.io \"k3s-control-node-plan\" not found, requeuing"
time="2022-08-30T17:30:10Z" level=error msg="error syncing 'system-upgrade/k3s-worker-plan': handler system-upgrade-controller: plans.upgrade.cattle.io \"k3s-worker-plan\" not found, requeuing"
time="2022-08-30T17:30:10Z" level=error msg="error syncing 'system-upgrade/k3s-control-node-plan': handler system-upgrade-controller: plans.upgrade.cattle.io \"k3s-control-node-plan\" not found, handler system-upgrade-controller: plans.upgrade.cattle.io \"k3s-control-node-plan\" not found, requeuing"
```
Simply killed `system-upgrade-controller` pod, and upon its restart, it immediately detected plan changes and got to to work...
```
time="2022-08-30T17:33:19Z" level=info msg="Applying CRD plans.upgrade.cattle.io"
time="2022-08-30T17:33:20Z" level=info msg="Starting /v1, Kind=Secret controller"
time="2022-08-30T17:33:20Z" level=info msg="Starting /v1, Kind=Node controller"
time="2022-08-30T17:33:20Z" level=info msg="Starting batch/v1, Kind=Job controller"
time="2022-08-30T17:33:20Z" level=info msg="Starting upgrade.cattle.io/v1, Kind=Plan controller"
```

After that nudge, everything upgraded fine.

```
$ k get nodes
NAME    STATUS   ROLES                       AGE    VERSION
k3s01   Ready    control-plane,etcd,master   151d   v1.24.4+k3s1
k3s02   Ready    control-plane,etcd,master   125d   v1.24.4+k3s1
k3s03   Ready    control-plane,etcd,master   132d   v1.24.4+k3s1
```
